
DROP TABLE IF EXISTS FriendList;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    id SERIAL PRIMARY KEY,
    username TEXT NULL,
    password TEXT NULL,
    auth_id TEXT NULL,
    firstname TEXT NULL,
    lastname TEXT NULL,
    gender TEXT NULL,
    haircolor TEXT NULL,
    eyecolor TEXT NULL,
    hobby TEXT NULL,
    birthmonth TEXT NULL,
    birthday INTEGER NULL,
    birthyear INTEGER NULL
);

CREATE TABLE FriendList(
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL
);


INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES ('Xena','WarriorPrincess','Female','Brown','Brown','Fishing','January',16,1984);

INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES ('Brita','Filter','Female','Blue','Blue','Fishing','June',23,1957);

INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES ('Billybob','Thornton','Male','Brown','Blue','Fishing','August',27,1964);

INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES ('Jakeumus','Maximus','Male','Brown','Brown','Video Games','March',16,1992);

INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES ('Gabrielle','Xenasidekick','Female','Blonde','Blue','Rafting','May',18,1995);


-- need to make create user and find user sql for auth0

INSERT INTO Users(
    firstname,
    lastname,
    gender,
    haircolor,
    eyecolor,
    hobby,
    birthmonth,
    birthday,
    birthyear)
VALUES 
    ('Gabrielle','Xenasidekick','Female','Blonde','Blue','Rafting','May',18,1995),
    ('AddieSofia', 'KaraNoelle', 'Male','Red','Green','Video Games','April', 14, 1952),
    ('MikeVladimir', 'ArdenLexi', 'Female','Red','Blue','Fishing','February', 28, 1939),
    ('BrunoMason', 'RosaarooNikki', 'Male','Brown','Brown','Video Games','May', 6, 1938),
    ('SueDeka', 'RonJona', 'Male','Brown','Green','Fishing','June', 6, 1944),
    ('KaiserJeremy', 'NaomiMike', 'Female','Red','Blue','Hiking','May', 7, 1938),
    ('JennyRia', 'SabrinaArlen', 'Male','Red','Green','Fishing','October', 5, 1997),
    ('TameraArron', 'KaiserLexi', 'Male','Red','Brown','Fishing','May', 21, 2010),
    ('JordanSadie', 'CatherineSabrina', 'Male','Green','Green','Hiking','March', 22, 1981),
    ('JessieAlejandro', 'AdolfLiz', 'Female','Red','Brown','Video Games','February', 28, 1958),
    ('KimikoNapolean', 'CindyJeremy', 'Female','Green','Green','Video Games','January', 4, 1959),
    ('JackieAlfanzzzzzzo', 'NapoleanKiana', 'Male','Brown','Brown','Video Games','September', 18, 1988),
    ('ArturoStalin', 'ArnaldoAsa', 'Female','Green','Green','Hiking','October', 16, 2006),
    ('RonCindy', 'JaneSharilyn', 'Female','Brown','Green','Hiking','May', 28, 1983),
    ('JennySonya', 'RosaarooTamera', 'Female','Blue','Blue','Hiking','May', 18, 2012),
    ('SageNina', 'ZuesSharmaine', 'Female','Red','Green','Hiking','May', 27, 1945),
    ('AlthaNapolean', 'KimikoSara', 'Male','Brown','Blue','Hiking','August', 15, 1943),
    ('DekaAndre', 'NottosmartbumRoselda', 'Male','Brown','Blue','Hiking','March', 27, 1928),
    ('AllieSabrina', 'LukeSara', 'Male','Brown','Brown','Video Games','May', 2, 1951),
    ('TorieTasia', 'KianaKimi', 'Male','Green','Brown','Video Games','July', 29, 2007),
    ('PoePopo', 'RosalvaNala', 'Female','Red','Brown','Fishing','April', 24, 1970),
    ('RalphChristy', 'NicoleKyle', 'Male','Red','Green','Fishing','February', 21, 2008),
    ('NadiaCatherine', 'JonChristie', 'Male','Blonde','Green','Video Games','April', 20, 1924),
    ('JennyGeorge', 'AlvaBarbara', 'Female','Brown','Blue','Fishing','July', 27, 1953),
    ('AldoArthur', 'JonasVladtheImpaler', 'Female','Green','Green','Fishing','May', 18, 1938),
    ('MasonToni', 'RosaarooErin', 'Female','Blonde','Blue','Hiking','June', 6, 2006),
    ('PoeAlec', 'RebeccaTaserface', 'Male','Blonde','Green','Video Games','September', 11, 1963),
    ('JonaErin', 'AnaPoe', 'Male','Brown','Brown','Video Games','August', 7, 1981),
    ('JessieJona', 'ShakiraChristy', 'Male','Green','Brown','Hiking','February', 10, 2004),
    ('ArlieBarbara', 'TiffanyNadia', 'Male','Blue','Blue','Hiking','July', 23, 1985),
    ('ZuesKara', 'TenishaJeremy', 'Female','Blue','Green','Hiking','April', 9, 1951),
    ('TrumpsterDebra', 'DictatorChristie', 'Female','Green','Brown','Video Games','August', 3, 2002),
    ('BrayanJoe', 'NapoleanNancy', 'Male','Green','Blue','Hiking','January', 3, 2000),
    ('NichelleVladtheImpaler', 'JosefAllie', 'Female','Red','Brown','Video Games','October', 11, 1957),
    ('SageAsa', 'SharilynRachel', 'Male','Red','Blue','Video Games','November', 21, 1940),
    ('NoelleRia', 'CindyAldo', 'Male','Blue','Green','Video Games','January', 30, 1946),
    ('KatrinaDebra', 'SageNichelle', 'Female','Blonde','Blue','Fishing','May', 19, 2004),
    ('RachelLloyd', 'TamiaArthur', 'Female','Blue','Green','Fishing','November', 7, 1976),
    ('KaiserBart', 'EsmereldaRebecca', 'Female','Red','Blue','Video Games','August', 16, 1988),
    ('ArthurErin', 'VladtheImpalerSharmaine', 'Female','Green','Green','Fishing','January', 27, 1984),
    ('KiaTonya', 'BarbaraRosalva', 'Female','Red','Blue','Hiking','February', 8, 1992),
    ('AugustineLiz', 'KeishaRosita', 'Male','Brown','Blue','Hiking','April', 29, 1922),
    ('ArthurDarla', 'ArlieShakira', 'Female','Blue','Brown','Hiking','January', 7, 1955),
    ('JoeAmos', 'ZuesAllen', 'Male','Blue','Brown','Video Games','March', 7, 1942),
    ('JeremyAnthony', 'SageNancy', 'Male','Red','Green','Video Games','August', 15, 1968),
    ('RonGeorgibush', 'AntonioSabrina', 'Female','Blue','Brown','Fishing','August', 21, 1926),
    ('RoseePolPot', 'JoeAlva', 'Female','Green','Blue','Video Games','February', 23, 1952),
    ('RavenLloyd', 'KiaRosee', 'Female','Blonde','Green','Fishing','September', 19, 1999),
    ('RikkiDarla', 'SadieSaddam', 'Male','Blue','Blue','Fishing','October', 18, 1947),
    ('AldoDeka', 'TamiaCatherine', 'Female','Brown','Green','Video Games','June', 7, 2007),
    ('JordanRia', 'NancyAnthony', 'Male','Blue','Green','Video Games','February', 15, 1993),
    ('AlfanzzzzzzoSilvia', 'RebeccaGeorgibush', 'Male','Blonde','Green','Hiking','August', 4, 1944),
    ('MasonSharmaine', 'Leopold2Joe', 'Female','Red','Brown','Fishing','July', 6, 2015),
    ('ToniEsmerelda', 'RonAndre', 'Female','Blonde','Green','Video Games','February', 19, 1990),
    ('KimberNaomi', 'PoppyCeline', 'Male','Brown','Green','Hiking','May', 9, 1950),
    ('JeremyHaedes', 'RiaKia', 'Female','Red','Brown','Fishing','October', 21, 1930),
    ('JordanDarla', 'KimberRosita', 'Male','Red','Green','Video Games','June', 1, 1978),
    ('StalinMozart', 'NalaAllen', 'Female','Red','Blue','Video Games','April', 8, 2011),
    ('TiffanySilvia', 'PolPotArron', 'Female','Blonde','Green','Fishing','August', 30, 1989),
    ('AlecKimJongUn', 'KyleNadia', 'Female','Blonde','Green','Fishing','July', 20, 1976),
    ('LeroyTenisha', 'ArdenHochinmin', 'Female','Brown','Brown','Video Games','June', 30, 1921),
    ('LizSabrina', 'RikkiDebra', 'Male','Blonde','Blue','Hiking','January', 12, 1935),
    ('NinaRosaaroo', 'TonyadorAugustine', 'Female','Green','Green','Video Games','September', 7, 1979),
    ('BarbaraAlfanzzzzzzo', 'SilviaTalia', 'Female','Red','Brown','Fishing','June', 2, 1956),
    ('PolPotNoelle', 'SofiaRia', 'Male','Red','Blue','Hiking','August', 3, 1936),
    ('AmmadRosalva', 'NapoleanRosee', 'Male','Blue','Blue','Hiking','October', 27, 1956),
    ('ArmoKimJongUn', 'SueRia', 'Female','Blonde','Green','Video Games','May', 19, 1999),
    ('NalaLegolas', 'RachelNaomi', 'Female','Blonde','Brown','Video Games','January', 16, 1975),
    ('TamiaCindy', 'TorieShakira', 'Female','Green','Brown','Fishing','June', 26, 2003),
    ('ArronToni', 'KatrinaJordan', 'Male','Blue','Brown','Video Games','May', 16, 1972),
    ('KeishaHochinmin', 'KimJongUnLexi', 'Male','Red','Green','Hiking','June', 6, 1918),
    ('ChiaraNadia', 'RachelSaddam', 'Male','Blonde','Green','Video Games','September', 29, 1969),
    ('HochinminChiara', 'LukeRosaaroo', 'Female','Red','Green','Video Games','August', 9, 1953),
    ('AldoNoelle', 'SharmaineCatherine', 'Female','Brown','Blue','Video Games','October', 11, 1949),
    ('BartMozart', 'BrunoAdam', 'Female','Brown','Brown','Fishing','August', 20, 1994),
    ('DarlaKimi', 'BrunoNancy', 'Male','Blue','Green','Fishing','November', 12, 1960),
    ('NoelleAlfanzzzzzzo', 'KiraShyla', 'Male','Blonde','Green','Video Games','October', 26, 1948),
    ('TennileArlen', 'TaliaRebecca', 'Male','Blue','Green','Video Games','February', 4, 1931),
    ('AlvaTonya', 'NicoleMike', 'Male','Blue','Green','Hiking','June', 5, 1918),
    ('KimbraAdam', 'TamiaTamia', 'Male','Brown','Green','Fishing','March', 30, 1936),
    ('DekaArmo', 'MikeArt', 'Female','Blue','Brown','Fishing','July', 2, 1935),
    ('AlejandroAddie', 'RonShyla', 'Female','Brown','Brown','Fishing','March', 7, 1970),
    ('KiaTasia', 'RebeccaKina', 'Female','Blonde','Brown','Hiking','October', 8, 1923),
    ('ArlieTennile', 'SebastianNaomi', 'Male','Red','Brown','Video Games','October', 4, 1934),
    ('PopoSage', 'JonAddie', 'Male','Red','Blue','Video Games','February', 28, 1973),
    ('BrayanVladimir', 'RoseldaSofia', 'Male','Brown','Green','Video Games','February', 26, 1936),
    ('RebeccaTrumpster', 'SharilynAmmad', 'Female','Red','Brown','Fishing','April', 28, 1955),
    ('KinaNapolean', 'CindyPolPot', 'Female','Red','Green','Fishing','September', 29, 1991),
    ('SharlaJose', 'Leopold2Darci', 'Male','Brown','Green','Video Games','April', 16, 1925),
    ('SonyaRackel', 'JennyTasia', 'Female','Blonde','Brown','Hiking','May', 18, 2014),
    ('SueNottosmartbum', 'TrumpsterKimSung', 'Female','Blue','Brown','Video Games','May', 3, 1990),
    ('ArthurAlejandro', 'JordanMike', 'Male','Blue','Green','Fishing','February', 4, 1922),
    ('AldoKara', 'Leopold2Rosita', 'Female','Red','Blue','Video Games','April', 19, 1998),
    ('XavierAllen', 'HaedesPolPot', 'Male','Green','Blue','Fishing','June', 15, 1956),
    ('ArronKyle', 'TonyaDictator', 'Male','Red','Green','Fishing','October', 13, 1949),
    ('GeorgeArt', 'LylaAdolf', 'Female','Brown','Brown','Video Games','April', 29, 1979),
    ('ArlenAlva', 'AlthaRosalva', 'Male','Red','Green','Video Games','March', 2, 1977),
    ('AdamJosef', 'AmmadKeisha', 'Female','Blonde','Brown','Hiking','March', 26, 1957),
    ('SilviaRia', 'SadiePolPot', 'Male','Blue','Blue','Hiking','January', 24, 1953),
    ('ArtDarryl', 'MatthewRaven', 'Male','Brown','Brown','Hiking','September', 26, 1927),
    ('SilviaDebra', 'AdolfSebastian', 'Female','Red','Blue','Hiking','April', 23, 1949),
    ('JackieArmo', 'TonyadorAltha', 'Female','Green','Brown','Fishing','January', 13, 1954),
    ('BethLexi', 'TiffanyTamera', 'Female','Green','Blue','Video Games','April', 9, 1941),
    ('NenitaTorie', 'LloydJon', 'Female','Blue','Blue','Fishing','October', 17, 1938),
    ('PoeKimber', 'JeremyJeremy', 'Male','Blonde','Green','Hiking','June', 23, 1924),
    ('JessicaRalph', 'KatrinaRosee', 'Male','Blue','Brown','Video Games','June', 13, 1953),
    ('LukeKimi', 'ErinTennile', 'Female','Blonde','Brown','Hiking','March', 21, 1969),
    ('JoeMike', 'BarbaraDarryl', 'Female','Brown','Green','Fishing','April', 4, 1949),
    ('SaraJon', 'SilviaXavier', 'Male','Green','Green','Fishing','October', 30, 1963),
    ('PopoJona', 'CatherineHaedes', 'Male','Brown','Brown','Hiking','February', 8, 1950),
    ('RoseeNatalia', 'AlvaRackel', 'Male','Brown','Blue','Video Games','August', 25, 1971),
    ('NaomiGeorge', 'SofiaKira', 'Male','Brown','Blue','Fishing','August', 10, 1934),
    ('HitlerRia', 'JosefBarbara', 'Male','Blonde','Brown','Fishing','June', 16, 1976),
    ('TenishaLiz', 'KaiserTasia', 'Male','Red','Brown','Fishing','May', 6, 1953),
    ('NenitaVladtheImpaler', 'SebastianKatrina', 'Female','Red','Green','Fishing','November', 6, 1925),
    ('LeroyPoe', 'AlvaLexi', 'Female','Blue','Green','Hiking','January', 21, 1920),
    ('RonSharla', 'ArthurHitler', 'Male','Red','Brown','Video Games','June', 26, 1992),
    ('MozartSabrina', 'TorieSansa', 'Female','Brown','Brown','Fishing','June', 15, 1919),
    ('KinaAdolf', 'NinaMason', 'Male','Red','Brown','Hiking','April', 8, 1924),
    ('CatherineJordan', 'AnaBarb', 'Male','Blonde','Green','Fishing','March', 7, 1975),
    ('TiffanyLloyd', 'StalinTrumpster', 'Female','Blonde','Blue','Video Games','February', 21, 1946),
    ('PopoTrumpster', 'EsmereldaMozart', 'Male','Green','Brown','Fishing','October', 13, 1939),
    ('AndreSharilyn', 'ToniKylee', 'Male','Green','Brown','Video Games','June', 7, 1987),
    ('CindyAldo', 'LeroyAsa', 'Male','Blue','Green','Fishing','May', 6, 1932),
    ('AndreBarb', 'SharmaineKia', 'Male','Blonde','Brown','Fishing','October', 30, 1952),
    ('RonEsmerelda', 'BrayanKimber', 'Female','Red','Brown','Video Games','November', 4, 1970),
    ('PoeTrumpster', 'NicoleKia', 'Female','Green','Brown','Video Games','February', 19, 2005),
    ('PoppyAdam', 'SonyaBruno', 'Female','Blonde','Blue','Hiking','August', 21, 1932),
    ('CelineAlec', 'SansaNichelle', 'Male','Blue','Brown','Hiking','November', 25, 2000),
    ('AsaRosee', 'AnaTamia', 'Female','Brown','Blue','Video Games','February', 2, 2000),
    ('LizLuke', 'AdamTonyador', 'Male','Red','Green','Video Games','March', 10, 1944),
    ('SabrinaLarry', 'KiraNaomi', 'Female','Blue','Green','Video Games','October', 26, 2004),
    ('DarrylHercules', 'DarlaCindy', 'Male','Brown','Brown','Fishing','September', 6, 1986),
    ('KatrinaDarci', 'RikkiBrayan', 'Female','Green','Blue','Video Games','April', 27, 2004),
    ('ChiaraXavier', 'RikkiArturo', 'Female','Green','Green','Video Games','January', 3, 1984),
    ('TsotsiBart', 'TameraErin', 'Male','Green','Brown','Hiking','October', 29, 1918),
    ('AlejandroLegolas', 'DarrylLarry', 'Female','Green','Green','Fishing','November', 29, 1936),
    ('BarbLexi', 'GeorgeJane', 'Female','Blue','Green','Hiking','August', 6, 1919),
    ('KimbraTsotsi', 'MatthewArt', 'Female','Brown','Brown','Hiking','August', 12, 2005),
    ('PoeTennile', 'AsaXavier', 'Male','Red','Brown','Fishing','November', 24, 1936),
    ('LizLexi', 'BarbRosalva', 'Male','Green','Brown','Hiking','June', 27, 1983),
    ('KimJongUnAddie', 'KaiserDarci', 'Male','Green','Green','Video Games','April', 6, 2000),
    ('Leopold2Natalia', 'KimberlyAllie', 'Male','Blonde','Brown','Video Games','September', 7, 1957),
    ('AmmadAddie', 'DarrylAldo', 'Female','Blue','Brown','Hiking','February', 25, 1926),
    ('BarbDebra', 'NoelleBeth', 'Female','Blonde','Brown','Hiking','May', 29, 1965),
    ('ZuesRachel', 'JonaXavier', 'Female','Blonde','Green','Fishing','March', 10, 1997),
    ('AllieLeroy', 'ArdenToni', 'Female','Blue','Green','Hiking','November', 16, 1920),
    ('CindyShakira', 'PoppyMason', 'Female','Red','Green','Fishing','January', 14, 1982),
    ('KyleKimber', 'HaedesNita', 'Male','Green','Green','Video Games','September', 11, 1942),
    ('SilviaDarryl', 'PoppyNaomi', 'Male','Green','Green','Video Games','August', 16, 1978),
    ('CelinePopo', 'HerculesLexi', 'Female','Blonde','Blue','Hiking','November', 7, 1960),
    ('NinaRikki', 'SadieNenita', 'Female','Red','Blue','Hiking','May', 29, 1922),
    ('GeorgibushBart', 'LylaRoselda', 'Male','Brown','Green','Fishing','April', 9, 1929),
    ('BartJon', 'CatherineAlva', 'Male','Blue','Brown','Hiking','June', 10, 1964),
    ('PolPotKylee', 'JameAna', 'Female','Green','Green','Video Games','January', 5, 1931),
    ('Leopold2Alva', 'DebraPopo', 'Male','Blonde','Blue','Video Games','March', 29, 1987),
    ('RosaarooKira', 'CelineNancy', 'Male','Blue','Brown','Fishing','October', 14, 1948),
    ('NaomiAllie', 'RositaHaedes', 'Male','Brown','Green','Hiking','February', 21, 1995),
    ('RalphArturo', 'SharlaDictator', 'Male','Green','Brown','Fishing','July', 6, 2003),
    ('PoeGeorge', 'ArmoTamera', 'Female','Green','Blue','Fishing','July', 12, 1922),
    ('LizSara', 'RihannaJefferey', 'Male','Blonde','Blue','Video Games','June', 5, 1942),
    ('CatherineNita', 'TamiaRackel', 'Female','Brown','Brown','Fishing','June', 10, 2008),
    ('AndrewKyle', 'KimiRosalva', 'Male','Red','Blue','Video Games','May', 30, 2014),
    ('SonyaAlejandro', 'ChristieHercules', 'Female','Blonde','Brown','Video Games','October', 29, 1954),
    ('RoseeDarla', 'BobJon', 'Female','Red','Blue','Fishing','January', 11, 1922),
    ('KaiserBarbara', 'DarciDarryl', 'Female','Blue','Blue','Hiking','February', 4, 1952),
    ('JameArmo', 'AnthonyNancy', 'Female','Green','Blue','Hiking','August', 23, 1993),
    ('RihannaTiffany', 'CelineRosita', 'Female','Blue','Green','Hiking','March', 6, 1974),
    ('AllenAsa', 'SofiaXavier', 'Male','Red','Brown','Hiking','May', 22, 1974),
    ('AllieNala', 'NitaJefferey', 'Male','Brown','Blue','Hiking','September', 16, 2011),
    ('JoleneNancy', 'ArturoSara', 'Female','Green','Brown','Video Games','March', 13, 1971),
    ('DarlaLiz', 'RiaSara', 'Male','Blonde','Blue','Video Games','May', 16, 1922),
    ('RebeccaBruno', 'AldoTenisha', 'Male','Blonde','Green','Fishing','March', 20, 1931),
    ('KeishaKeisha', 'KathleenNicole', 'Female','Red','Brown','Hiking','June', 17, 1947),
    ('RoseldaAddie', 'NicoleAndre', 'Male','Blonde','Blue','Video Games','September', 21, 1925),
    ('SaraSebastian', 'AllieSabrina', 'Female','Blonde','Green','Video Games','September', 20, 1974),
    ('TaserfaceArlie', 'KatrinaErin', 'Female','Blue','Green','Video Games','March', 21, 2004),
    ('NaomiKira', 'RonAlva', 'Male','Blonde','Brown','Video Games','June', 23, 1951),
    ('TorieShakira', 'CindyRalph', 'Female','Blue','Brown','Hiking','June', 20, 1969),
    ('TamiaJoe', 'VladimirShyla', 'Male','Blue','Brown','Video Games','April', 15, 1972),
    ('KimSungJolene', 'SilviaNapolean', 'Male','Blue','Green','Video Games','March', 7, 1918),
    ('RoseeTonyador', 'HerculesChiara', 'Male','Green','Green','Hiking','July', 6, 1953),
    ('JeremyJoe', 'ArmoAldo', 'Male','Blue','Green','Fishing','January', 11, 1991),
    ('PolPotKimSung', 'TsotsiVladtheImpaler', 'Female','Blue','Green','Fishing','October', 7, 1971),
    ('TamiaKaiser', 'KimberlyNenita', 'Female','Blonde','Brown','Hiking','January', 15, 1957),
    ('LloydToni', 'NenitaSaddam', 'Female','Blue','Brown','Hiking','July', 17, 1983),
    ('NichelleJona', 'ShylaAsa', 'Male','Green','Brown','Fishing','April', 26, 1955),
    ('SansaRon', 'DebraAldo', 'Male','Brown','Blue','Video Games','April', 1, 2013),
    ('KeishaAsa', 'SharilynTamera', 'Male','Blue','Green','Hiking','October', 30, 1952),
    ('GeorgeRosita', 'RachelJonas', 'Male','Brown','Brown','Video Games','October', 24, 1922),
    ('NichelleTenisha', 'RosaarooJessie', 'Male','Red','Green','Hiking','February', 25, 1932),
    ('DollyTorie', 'XavierAndre', 'Male','Brown','Brown','Video Games','June', 23, 1985),
    ('AddieAltha', 'AsaAndre', 'Male','Blue','Green','Video Games','October', 27, 1943),
    ('SadieAugustine', 'LegolasCeline', 'Male','Blonde','Brown','Video Games','May', 7, 1956),
    ('KathleenGeorge', 'RosaarooKimberly', 'Male','Red','Green','Fishing','May', 2, 2016),
    ('AdamDebra', 'NichelleArden', 'Female','Red','Green','Video Games','March', 19, 1936),
    ('JessicaNina', 'NataliaRia', 'Female','Blonde','Brown','Fishing','November', 30, 1928),
    ('MikeNikki', 'MozartAmmad', 'Male','Red','Green','Video Games','September', 4, 1960),
    ('HollyNatalia', 'GeorgeJessica', 'Female','Brown','Brown','Hiking','June', 15, 1977),
    ('MozartEsmerelda', 'NinaAllie', 'Male','Green','Green','Video Games','July', 7, 1994),
    ('JessieBarb', 'JaneBrayan', 'Male','Red','Brown','Hiking','February', 24, 2011),
    ('RoseldaNala', 'ArtMason', 'Female','Red','Green','Fishing','May', 23, 2010),
    ('AugustineSadie', 'ArlieErin', 'Female','Brown','Green','Hiking','August', 5, 2015),
    ('GeorgeMike', 'JonaAna', 'Female','Red','Green','Hiking','July', 23, 2008),
    ('PoeJosef', 'StalinAlfanzzzzzzo', 'Male','Green','Green','Hiking','August', 26, 1931),
    ('StalinDictator', 'KiraAndrew', 'Male','Green','Brown','Video Games','March', 21, 1928),
    ('MasonAlfanzzzzzzo', 'EsmereldaVladimir', 'Male','Brown','Brown','Fishing','January', 22, 1958),
    ('AnaKeisha', 'KeishaJoe', 'Female','Brown','Green','Video Games','May', 28, 1955),
    ('KimberArmo', 'BethCeline', 'Male','Blue','Blue','Hiking','November', 14, 2014),
    ('RosaarooJessica', 'RosaarooGeorgibush', 'Male','Blue','Green','Video Games','June', 28, 1970),
    ('ArdenSilvia', 'ShylaTrumpster', 'Female','Blonde','Green','Fishing','April', 15, 1961),
    ('JonRia', 'NottosmartbumTamia', 'Female','Blonde','Green','Video Games','October', 3, 1971),
    ('DarrylSage', 'EsmereldaDebra', 'Female','Brown','Blue','Video Games','May', 24, 1932),
    ('RebeccaAlejandro', 'VladtheImpalerRosalva', 'Female','Brown','Green','Hiking','November', 10, 1952),
    ('JackieAddie', 'ChristieRosalva', 'Female','Red','Green','Video Games','April', 25, 1989),
    ('DarlaBarb', 'LexiNenita', 'Female','Red','Blue','Hiking','June', 4, 1984),
    ('RachelCeline', 'NikkiCindy', 'Male','Blue','Brown','Hiking','October', 16, 1974),
    ('NinaBarb', 'GeorgeDebra', 'Female','Green','Brown','Hiking','November', 19, 1926),
    ('MozartNina', 'KiaDebbie', 'Male','Blonde','Blue','Fishing','May', 4, 1938),
    ('SansaKaiser', 'NapoleanCatherine', 'Male','Blue','Green','Fishing','April', 9, 1929),
    ('NitaAugustine', 'StalinShyla', 'Male','Brown','Blue','Fishing','May', 15, 1970),
    ('AlvaTiffany', 'SadieVladimir', 'Male','Blonde','Green','Video Games','May', 1, 1931),
    ('TsotsiLiz', 'LizXavier', 'Male','Red','Blue','Hiking','November', 11, 1957),
    ('JeffereyAndre', 'NitaKimber', 'Female','Brown','Blue','Video Games','October', 12, 1999),
    ('LegolasKimi', 'CindyKathleen', 'Female','Blonde','Brown','Video Games','August', 25, 2009),
    ('DekaLegolas', 'KaiserTorie', 'Female','Blue','Blue','Video Games','November', 14, 1989),
    ('NataliaNichelle', 'KimbraAltha', 'Female','Blue','Brown','Video Games','October', 21, 1988),
    ('NoelleNatalia', 'SofiaLarry', 'Female','Green','Blue','Video Games','February', 16, 1929),
    ('DarciVladimir', 'SonyaAugustine', 'Male','Blonde','Green','Fishing','March', 15, 2008),
    ('JaneBob', 'AntonioTsotsi', 'Male','Blonde','Green','Video Games','January', 25, 1984),
    ('SebastianKiana', 'RalphMike', 'Female','Red','Brown','Video Games','September', 5, 1971),
    ('AllenShyla', 'KatrinaTiffany', 'Male','Blonde','Blue','Video Games','May', 1, 2006),
    ('AndrewNichelle', 'NaomiJonas', 'Female','Blue','Green','Video Games','March', 4, 1927),
    ('BarbSharla', 'DebraCeline', 'Male','Blue','Brown','Hiking','September', 4, 1944),
    ('TonyaChiara', 'AndreLloyd', 'Female','Blue','Brown','Hiking','September', 3, 1972),
    ('KaiserPolPot', 'RikkiChristie', 'Female','Blue','Blue','Hiking','May', 22, 1954),
    ('TennileAmmad', 'AnaDeka', 'Male','Brown','Brown','Hiking','June', 1, 1988),
    ('LegolasShyla', 'MozartAlva', 'Male','Blue','Brown','Fishing','May', 29, 1927),
    ('LylaKimi', 'GeorgeHitler', 'Male','Brown','Blue','Fishing','August', 24, 2008),
    ('NancyAdam', 'TorieTaserface', 'Male','Blue','Brown','Hiking','October', 18, 1925),
    ('NapoleanNoelle', 'LizAntonio', 'Female','Blonde','Brown','Video Games','May', 13, 1997),
    ('LylaChristie', 'TonyadorKia', 'Female','Blue','Blue','Fishing','April', 20, 1930),
    ('NoraNala', 'ArmoTenisha', 'Female','Blonde','Brown','Hiking','November', 14, 1987),
    ('LukeNikki', 'ArmoAmmad', 'Female','Brown','Green','Hiking','September', 9, 1939),
    ('ArdenTennile', 'PolPotBart', 'Male','Blonde','Green','Hiking','August', 8, 1979),
    ('ChiaraDictator', 'JordanHolly', 'Male','Red','Blue','Fishing','November', 30, 1975),
    ('SharmaineDolly', 'RackelBarbara', 'Male','Blue','Blue','Hiking','June', 25, 1921),
    ('AddieToni', 'BrunoHercules', 'Female','Blonde','Green','Hiking','July', 16, 1951),
    ('NaomiDeka', 'SageJoe', 'Male','Blue','Blue','Hiking','November', 30, 1951),
    ('AsaAlva', 'GeorgeAmmad', 'Male','Green','Blue','Video Games','November', 25, 1987),
    ('TenishaHercules', 'RavenJosef', 'Female','Red','Brown','Video Games','March', 29, 1948),
    ('EsmereldaHercules', 'KyleAdam', 'Female','Blonde','Brown','Video Games','February', 25, 2011),
    ('RikkiDolly', 'NapoleanCatherine', 'Female','Brown','Green','Hiking','September', 17, 1957),
    ('AugustineArnaldo', 'DollyLiz', 'Male','Red','Blue','Video Games','June', 18, 1970),
    ('AllieArlen', 'TaliaHaedes', 'Male','Brown','Brown','Hiking','August', 20, 1986),
    ('RebeccaKimber', 'AlthaJose', 'Male','Red','Green','Video Games','July', 6, 1920),
    ('AnthonySharla', 'KiraLloyd', 'Male','Red','Blue','Fishing','June', 9, 1971),
    ('SansaLexi', 'KeishaLegolas', 'Male','Brown','Brown','Fishing','September', 5, 1946),
    ('BarbaraJane', 'DarciDarryl', 'Female','Brown','Brown','Fishing','May', 9, 1943),
    ('ShylaRosalva', 'KiraVladimir', 'Male','Green','Green','Fishing','September', 17, 1936),
    ('TaserfaceLiz', 'StalinNina', 'Male','Green','Green','Fishing','July', 1, 2010),
    ('LylaRachel', 'SansaChiara', 'Female','Brown','Brown','Video Games','March', 19, 1987),
    ('TrumpsterRosee', 'JordanDictator', 'Female','Red','Blue','Fishing','January', 16, 2008),
    ('GeorgeRaven', 'BarbTenisha', 'Male','Blonde','Blue','Hiking','November', 18, 1919),
    ('AlfanzzzzzzoNatalia', 'BrayanArt', 'Female','Blue','Green','Fishing','October', 26, 1953),
    ('KimikoToni', 'EsmereldaAlfanzzzzzzo', 'Female','Blonde','Green','Video Games','June', 7, 1975),
    ('RosaarooAdolf', 'LegolasSadie', 'Male','Green','Blue','Video Games','May', 6, 1971),
    ('AntonioBarbara', 'PoeSara', 'Female','Red','Brown','Fishing','September', 1, 1939),
    ('PoppyNaomi', 'LloydSadie', 'Male','Brown','Blue','Hiking','September', 25, 1918),
    ('KimikoRon', 'LylaCatherine', 'Female','Red','Brown','Fishing','July', 23, 2016),
    ('AmosStalin', 'PopoTonyador', 'Female','Green','Brown','Hiking','January', 26, 1939),
    ('ZuesJolene', 'RavenRikki', 'Female','Green','Blue','Fishing','July', 19, 2007),
    ('KimJongUnRikki', 'HitlerHolly', 'Male','Brown','Blue','Video Games','June', 17, 1937),
    ('KimbraNora', 'SageNicole', 'Female','Green','Brown','Video Games','October', 15, 1962),
    ('ArlieTamera', 'SaraMike', 'Male','Blonde','Brown','Video Games','July', 19, 1958),
    ('NataliaAmmad', 'MatthewHercules', 'Female','Brown','Green','Hiking','April', 26, 1958),
    ('JameAdam', 'TennileTsotsi', 'Female','Brown','Brown','Fishing','April', 19, 1925),
    ('KimbraMatthew', 'JoseXavier', 'Male','Red','Brown','Hiking','July', 11, 1999),
    ('MikeTalia', 'XavierKimberly', 'Male','Red','Brown','Hiking','October', 25, 1932),
    ('SharlaJon', 'SharmaineJose', 'Female','Blonde','Blue','Video Games','October', 11, 1966),
    ('CatherineRachel', 'LukeTenisha', 'Male','Green','Brown','Fishing','January', 30, 2001),
    ('JonChristy', 'HollyNapolean', 'Female','Green','Blue','Video Games','June', 20, 1995),
    ('JoeVladimir', 'TrumpsterGeorgibush', 'Female','Blonde','Brown','Fishing','August', 29, 1937),
    ('LarryRon', 'LizStalin', 'Female','Blonde','Green','Hiking','June', 28, 1937),
    ('SadieLiz', 'JonasNottosmartbum', 'Male','Green','Brown','Video Games','August', 28, 1979),
    ('NichelleTasia', 'TiffanyKina', 'Female','Green','Blue','Fishing','July', 18, 1932),
    ('AmosLarry', 'JessieAndrew', 'Male','Brown','Blue','Fishing','January', 11, 1995),
    ('NichelleAndre', 'SageDebra', 'Female','Blue','Blue','Fishing','March', 7, 1969),
    ('DictatorAlva', 'AntonioLarry', 'Female','Red','Brown','Fishing','June', 3, 1989),
    ('GeorgibushArthur', 'JonasTasia', 'Female','Red','Blue','Video Games','April', 28, 1993),
    ('TiffanyNapolean', 'KianaRosalva', 'Female','Green','Blue','Video Games','April', 6, 1933),
    ('AlvaKara', 'ChristyTalia', 'Female','Blue','Green','Fishing','April', 16, 2013),
    ('JonaKyle', 'AlthaSilvia', 'Female','Brown','Green','Hiking','February', 9, 1970),
    ('LegolasToni', 'RikkiSue', 'Female','Blue','Blue','Video Games','April', 23, 1997),
    ('MatthewNikki', 'CatherineRachel', 'Female','Blonde','Brown','Hiking','May', 14, 1932),
    ('ChristyKaiser', 'LexiKimber', 'Female','Blonde','Blue','Fishing','June', 6, 1941),
    ('AddieRon', 'LexiNaomi', 'Male','Red','Green','Hiking','January', 19, 1942),
    ('NenitaRia', 'KimberAsa', 'Female','Red','Blue','Fishing','August', 23, 1972),
    ('NicoleTalia', 'KimiNikki', 'Male','Blue','Green','Video Games','October', 6, 2004),
    ('JeremyCatherine', 'SharmaineAugustine', 'Male','Blue','Green','Video Games','April', 12, 1973),
    ('LizLegolas', 'TasiaNapolean', 'Female','Red','Blue','Hiking','January', 6, 1992),
    ('JonPopo', 'RoseldaAdam', 'Female','Brown','Blue','Fishing','April', 9, 2012),
    ('RiaRoselda', 'TasiaRebecca', 'Male','Blonde','Blue','Fishing','November', 21, 1980),
    ('AmmadAlva', 'AdolfTamia', 'Female','Blonde','Blue','Hiking','November', 25, 1967),
    ('NichelleCatherine', 'StalinAllie', 'Male','Red','Green','Fishing','May', 10, 1981),
    ('JessieNichelle', 'KeishaAntonio', 'Female','Green','Brown','Video Games','February', 22, 2014),
    ('ToniNoelle', 'RikkiTaserface', 'Female','Green','Blue','Video Games','April', 10, 2006),
    ('BrayanLyla', 'GeorgeArturo', 'Female','Green','Brown','Hiking','August', 2, 1950),
    ('AndreKyle', 'XavierRon', 'Female','Blonde','Blue','Hiking','March', 26, 1967),
    ('ArlenArron', 'KimberlyAmmad', 'Male','Red','Brown','Video Games','November', 12, 1990),
    ('LylaTenisha', 'JackieKimber', 'Female','Red','Brown','Video Games','March', 22, 1966),
    ('ShakiraTenisha', 'NancyLuke', 'Female','Green','Blue','Video Games','November', 4, 1966),
    ('RachelNina', 'RoseeGeorge', 'Male','Blue','Green','Fishing','February', 27, 1932),
    ('RihannaSharilyn', 'AlecDebra', 'Female','Blonde','Brown','Fishing','September', 2, 1925),
    ('TasiaAmos', 'JaneSage', 'Female','Red','Brown','Fishing','June', 26, 2013),
    ('NikkiNita', 'EsmereldaLarry', 'Male','Brown','Green','Video Games','August', 7, 1988),
    ('RosalvaToni', 'NaomiNicole', 'Female','Red','Brown','Video Games','September', 15, 1970),
    ('DarciKeisha', 'JackieKeisha', 'Male','Red','Green','Hiking','March', 21, 1973),
    ('AntonioAdolf', 'JosefNoelle', 'Female','Red','Blue','Fishing','April', 2, 1936),
    ('KaraBruno', 'JosefErin', 'Female','Blonde','Green','Video Games','April', 21, 1954),
    ('MatthewDolly', 'TamiaPolPot', 'Female','Blonde','Blue','Hiking','June', 3, 1961),
    ('DarlaNoelle', 'JackieSharmaine', 'Male','Blonde','Green','Fishing','September', 3, 1967),
    ('AndrewNicole', 'EsmereldaKathleen', 'Female','Green','Blue','Fishing','January', 11, 1977),
    ('NenitaRosaaroo', 'KathleenKia', 'Male','Green','Green','Video Games','August', 8, 1940),
    ('AsaSansa', 'LloydSilvia', 'Female','Blonde','Brown','Hiking','January', 11, 1969),
    ('CelineAndre', 'ArlieNina', 'Male','Blue','Blue','Video Games','August', 16, 1936),
    ('JoeStalin', 'KimbraDarci', 'Male','Brown','Green','Fishing','June', 18, 2000),
    ('NapoleanKimiko', 'TonyaAlec', 'Female','Blonde','Green','Video Games','July', 28, 1991),
    ('KyleeCeline', 'AllenStalin', 'Male','Red','Green','Video Games','November', 30, 1922),
    ('HaedesSonya', 'KeishaAndrew', 'Male','Blonde','Brown','Hiking','September', 25, 1988),
    ('JessicaTasia', 'ArlenKira', 'Male','Blue','Blue','Fishing','October', 10, 1989),
    ('RihannaArlie', 'HollyKara', 'Female','Brown','Brown','Video Games','July', 6, 2013),
    ('ErinNikki', 'ArdenKiana', 'Female','Brown','Blue','Video Games','November', 8, 1970),
    ('SharmaineRebecca', 'TaserfaceBarbara', 'Female','Blue','Green','Fishing','August', 10, 1977),
    ('KaiserTiffany', 'ToniKyle', 'Female','Brown','Blue','Hiking','January', 5, 1937),
    ('TonyaNoelle', 'JaneHochinmin', 'Male','Blonde','Blue','Hiking','May', 20, 1922),
    ('KimJongUnJonas', 'JackieNancy', 'Female','Brown','Blue','Video Games','March', 2, 1924),
    ('ArturoSonya', 'TonyaTenisha', 'Female','Blue','Blue','Hiking','August', 22, 1977),
    ('EsmereldaAllen', 'JackieJona', 'Female','Green','Brown','Hiking','August', 24, 1954),
    ('AndrewDarryl', 'TamiaTonyador', 'Male','Blue','Brown','Fishing','October', 30, 1933),
    ('RackelNina', 'DarrylJenny', 'Female','Red','Brown','Hiking','June', 8, 1952),
    ('NalaRosita', 'DekaJessica', 'Male','Blonde','Blue','Hiking','October', 9, 2016),
    ('RositaAddie', 'AntonioDarryl', 'Male','Brown','Blue','Video Games','September', 30, 1979),
    ('AnthonyPopo', 'BarbaraKimberly', 'Male','Blue','Green','Fishing','November', 13, 1948),
    ('RoseldaJackie', 'JameBeth', 'Female','Red','Blue','Video Games','July', 12, 2016),
    ('JeremyTsotsi', 'BarbaraJackie', 'Female','Blue','Brown','Video Games','August', 19, 2012),
    ('AnaNapolean', 'AdolfArnaldo', 'Female','Blonde','Brown','Video Games','October', 25, 1997),
    ('AllieRon', 'AlecLloyd', 'Female','Blonde','Brown','Video Games','July', 29, 2006),
    ('HerculesNatalia', 'TaliaJackie', 'Male','Blonde','Green','Video Games','June', 2, 2009),
    ('NikkiKimiko', 'RavenGeorge', 'Female','Green','Green','Fishing','January', 17, 1925),
    ('AllenAllie', 'SharilynDarci', 'Male','Green','Blue','Fishing','November', 22, 1950),
    ('StalinRon', 'DarlaDarla', 'Male','Green','Green','Fishing','February', 23, 1945),
    ('ErinRia', 'JoeMozart', 'Female','Blonde','Brown','Video Games','November', 6, 2001),
    ('ArronNadia', 'JameArron', 'Female','Blonde','Green','Video Games','July', 6, 1977),
    ('KinaKathleen', 'JoleneAlejandro', 'Female','Blue','Green','Hiking','June', 12, 1955),
    ('NoelleStalin', 'AnaPoppy', 'Female','Blue','Green','Video Games','March', 1, 1988),
    ('LloydKiana', 'TonyaZues', 'Male','Red','Green','Video Games','May', 9, 1931),
    ('AldoAldo', 'DollyLloyd', 'Female','Blonde','Blue','Video Games','February', 7, 1978),
    ('JoeJenny', 'AntonioBruno', 'Female','Blue','Brown','Fishing','November', 17, 1968),
    ('HitlerTenisha', 'KathleenRalph', 'Male','Blonde','Green','Hiking','January', 15, 1999),
    ('DebbieAmos', 'RikkiTorie', 'Female','Blonde','Brown','Hiking','November', 12, 1964),
    ('NapoleanBarb', 'TamiaTamia', 'Female','Blue','Blue','Hiking','June', 29, 1976),
    ('GeorgibushKara', 'RonDarci', 'Male','Green','Brown','Fishing','March', 16, 1924),
    ('AntonioNikki', 'JessieNala', 'Male','Green','Blue','Video Games','June', 22, 1975),
    ('DollyNoelle', 'ArlieRikki', 'Female','Blonde','Blue','Fishing','May', 20, 1963),
    ('AddieAmmad', 'KimbraShyla', 'Female','Green','Blue','Fishing','January', 9, 2012),
    ('KimSungTonya', 'TiffanyTiffany', 'Male','Red','Green','Hiking','March', 19, 2003),
    ('TonyaArnaldo', 'GeorgibushRachel', 'Female','Brown','Brown','Video Games','November', 25, 1922),
    ('BrayanXavier', 'SilviaNapolean', 'Female','Green','Green','Video Games','August', 14, 1975),
    ('NenitaShyla', 'AnaAddie', 'Female','Brown','Green','Video Games','July', 26, 2010),
    ('LeroyArron', 'SansaSage', 'Male','Red','Green','Fishing','September', 1, 1955),
    ('BarbRaven', 'NalaAddie', 'Male','Blue','Brown','Video Games','August', 25, 2012),
    ('AdolfVladtheImpaler', 'EsmereldaLiz', 'Female','Red','Green','Fishing','September', 26, 1974),
    ('KaraVladimir', 'ArdenLyla', 'Female','Brown','Blue','Video Games','November', 19, 1999),
    ('HochinminRikki', 'RavenHochinmin', 'Female','Red','Brown','Video Games','January', 17, 1950),
    ('KyleeXavier', 'ArnaldoKimber', 'Male','Blonde','Green','Video Games','July', 19, 1944),
    ('HitlerJessie', 'ChristieNichelle', 'Male','Red','Green','Video Games','September', 19, 2010),
    ('SadieAddie', 'PolPotJessica', 'Male','Green','Green','Fishing','September', 23, 1939),
    ('RachelJona', 'NottosmartbumBob', 'Male','Brown','Brown','Fishing','July', 24, 1959),
    ('JessieJenny', 'NottosmartbumHitler', 'Female','Blonde','Blue','Hiking','January', 19, 1976),
    ('DarlaJenny', 'KimberlyRihanna', 'Male','Green','Green','Hiking','March', 2, 1931),
    ('BrayanSebastian', 'JoleneNenita', 'Female','Blue','Blue','Video Games','September', 12, 1991),
    ('KianaTasia', 'RackelTonya', 'Female','Red','Blue','Video Games','April', 22, 2012),
    ('KathleenKyle', 'SageChristie', 'Male','Red','Green','Video Games','November', 28, 1993),
    ('KeishaLexi', 'KimberlyAdam', 'Female','Brown','Green','Hiking','June', 28, 1941),
    ('JameBarbara', 'JonTaserface', 'Male','Green','Brown','Video Games','May', 19, 2008),
    ('TorieLuke', 'SansaDarryl', 'Male','Green','Blue','Fishing','November', 24, 1969),
    ('DebraTiffany', 'SadieNaomi', 'Female','Blue','Green','Hiking','October', 20, 1929),
    ('RosalvaPolPot', 'KimiPolPot', 'Male','Blonde','Blue','Hiking','August', 24, 1969),
    ('AdamBrayan', 'KimikoTrumpster', 'Female','Red','Blue','Hiking','July', 21, 1973),
    ('ErinKyle', 'KimSungTiffany', 'Male','Blue','Brown','Fishing','November', 17, 1940),
    ('KaraRachel', 'TennileSansa', 'Male','Green','Green','Hiking','January', 11, 1941),
    ('PolPotPolPot', 'AmosAdam', 'Female','Blue','Green','Fishing','November', 27, 1945),
    ('DictatorChiara', 'AlvaHaedes', 'Female','Blonde','Blue','Hiking','October', 24, 1962),
    ('KatrinaKimSung', 'ErinTrumpster', 'Male','Blue','Blue','Hiking','June', 4, 1988),
    ('SebastianAmos', 'SabrinaJefferey', 'Male','Blonde','Green','Video Games','August', 1, 1991),
    ('LukeNicole', 'JoseNicole', 'Male','Brown','Blue','Hiking','June', 15, 1924),
    ('MikeLloyd', 'AmosArmo', 'Female','Blonde','Brown','Hiking','August', 24, 1956),
    ('DebraNala', 'AnaTenisha', 'Female','Blue','Green','Video Games','November', 11, 1980),
    ('JessieJefferey', 'KyleeKia', 'Male','Green','Brown','Video Games','January', 25, 1996),
    ('HitlerJordan', 'NancyNenita', 'Female','Blonde','Green','Video Games','October', 28, 1988),
    ('ArthurAlejandro', 'ShylaTennile', 'Male','Red','Brown','Video Games','January', 24, 1942),
    ('Leopold2Kiana', 'ZuesLyla', 'Female','Blonde','Brown','Video Games','February', 10, 1974),
    ('NoelleAmmad', 'BrunoHitler', 'Female','Brown','Green','Hiking','April', 1, 1920),
    ('AdamAsa', 'SilviaTamera', 'Female','Green','Green','Hiking','August', 2, 1950),
    ('ShylaNapolean', 'TrumpsterLegolas', 'Male','Red','Brown','Video Games','May', 26, 1923),
    ('VladimirSue', 'NataliaAnthony', 'Female','Green','Brown','Video Games','September', 14, 1950),
    ('AndrePolPot', 'RiaKara', 'Male','Blonde','Blue','Fishing','November', 20, 1970),
    ('MikeTalia', 'ZuesChristy', 'Male','Brown','Blue','Fishing','January', 28, 1931),
    ('HerculesNadia', 'LloydRebecca', 'Female','Brown','Blue','Hiking','August', 29, 1929),
    ('ArtSonya', 'JoePolPot', 'Male','Blue','Green','Fishing','May', 14, 1928),
    ('RositaAlejandro', 'TaliaCindy', 'Female','Brown','Blue','Hiking','May', 29, 1968),
    ('RackelArt', 'TiffanyLuke', 'Female','Green','Blue','Fishing','November', 22, 1933),
    ('PoppyArturo', 'TasiaXavier', 'Female','Brown','Blue','Fishing','March', 15, 1941),
    ('NalaErin', 'HitlerSansa', 'Male','Brown','Brown','Video Games','May', 28, 1919),
    ('RositaLeopold2', 'PopoAldo', 'Female','Blue','Green','Video Games','April', 23, 1929),
    ('AllenArturo', 'DekaJeremy', 'Male','Blue','Blue','Fishing','January', 29, 1947),
    ('ChiaraXavier', 'AddieRalph', 'Female','Blonde','Green','Video Games','July', 27, 1919),
    ('RihannaJane', 'JoleneKatrina', 'Male','Brown','Blue','Fishing','October', 15, 1952),
    ('RosaarooAmmad', 'AlecSonya', 'Male','Blue','Brown','Fishing','August', 2, 1992),
    ('TennileDolly', 'KatrinaXavier', 'Male','Blue','Green','Video Games','June', 1, 1984),
    ('NancyJoe', 'AdamHaedes', 'Male','Green','Green','Fishing','April', 18, 1959),
    ('TonyadorHercules', 'LarryAlejandro', 'Male','Brown','Blue','Fishing','August', 15, 1955),
    ('JameRaven', 'RalphAsa', 'Male','Brown','Brown','Hiking','April', 17, 1930)






